# Generated by Django 5.2.4 on 2025-07-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="event_images/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ALL", "All Events"),
                            ("COA", "COA Events"),
                            ("LIONS", "LIONS Events"),
                        ],
                        default="ALL",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
