# Generated by Django 5.2.4 on 2025-07-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_remove_eventcard_category_eventcard_tag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventcard",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="event_images/"),
        ),
        migrations.AlterField(
            model_name="eventcard",
            name="tag",
            field=models.CharField(
                blank=True,
                choices=[("LIONS", "LIONS"), ("COA", "COA")],
                max_length=10,
                null=True,
            ),
        ),
    ]
