# Generated by Django 5.2.4 on 2025-07-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_eventcard_image_alter_eventcard_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventcard",
            name="tag",
            field=models.CharField(
                choices=[("LIONS", "LIONS"), ("COA", "COA")],
                default="LIONS",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="eventcard",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
