# Generated by Django 5.2.4 on 2025-07-14 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_eventcard_tag_alter_eventcard_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventcard",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime(2025, 7, 14, 0, 0)
            ),
            preserve_default=False,
        ),
    ]
