# Generated by Django 5.2.4 on 2025-07-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_eventcard_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventcard",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Talk", "Talk"),
                    ("Concert", "Concert"),
                    ("Conference", "Conference"),
                    ("Party", "Party"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventcard",
            name="created_at",
            field=models.DateField(verbose_name="Event Date"),
        ),
    ]
