# Generated by Django 5.2.4 on 2025-07-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_eventcard_type_alter_eventcard_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventcard",
            name="created_at",
            field=models.DateTimeField(verbose_name="Event Date and Time"),
        ),
    ]
