# Generated by Django 5.2.4 on 2025-07-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_alter_eventcard_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventcard",
            name="hosted_by",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
